import React, {useEffect, useMemo, useState} from "react";

const KEY="modren_bank_v4";
const languages={
  en:{name:"English",dir:"ltr",t:{bank:"Modren Bank",dashboard:"Dashboard",users:"Users",games:"Games",currencies:"Currencies",shop:"Shop",transactions:"Transactions",permissions:"Permissions",settings:"Settings",backup:"Backup",login:"Sign in",createAdmin:"Create administrator",username:"Username",password:"Password",confirm:"Confirm password",logout:"Log out",add:"Add",delete:"Delete",freeze:"Freeze",active:"Active",frozen:"Frozen",banned:"Banned",save:"Save",language:"Language",theme:"Theme",dark:"Dark",light:"Light",warning:"Local browser storage only",newUser:"New user",newGame:"New game",newCurrency:"New currency",newProduct:"New product",name:"Name",email:"Email",code:"Game ID / Code",symbol:"Symbol",price:"Price",description:"Description",role:"Role",admin:"Admin",user:"User",noData:"No data yet",export:"Export backup",import:"Import backup",deleteAccount:"Delete my account",search:"Search",version:"Version",updateUrl:"Update URL",local:"Local-only mode"}},
  ar:{name:"العربية",dir:"rtl",t:{bank:"Modren Bank",dashboard:"الرئيسية",users:"المستخدمون",games:"الألعاب",currencies:"العملات",shop:"المتجر",transactions:"المعاملات",permissions:"الصلاحيات",settings:"الإعدادات",backup:"النسخ الاحتياطي",login:"تسجيل الدخول",createAdmin:"إنشاء المدير",username:"اسم المستخدم",password:"كلمة المرور",confirm:"تأكيد كلمة المرور",logout:"تسجيل الخروج",add:"إضافة",delete:"حذف",freeze:"تجميد",active:"نشط",frozen:"مجمّد",banned:"محظور",save:"حفظ",language:"اللغة",theme:"المظهر",dark:"داكن",light:"فاتح",warning:"التخزين محلي داخل المتصفح فقط",newUser:"مستخدم جديد",newGame:"لعبة جديدة",newCurrency:"عملة جديدة",newProduct:"منتج جديد",name:"الاسم",email:"البريد",code:"معرّف / رمز اللعبة",symbol:"الرمز",price:"السعر",description:"الوصف",role:"الدور",admin:"مدير",user:"مستخدم",noData:"لا توجد بيانات بعد",export:"تصدير نسخة",import:"استيراد نسخة",deleteAccount:"حذف حسابي",search:"بحث",version:"الإصدار",updateUrl:"رابط التحديث",local:"وضع محلي فقط"}},
  fr:{name:"Français",dir:"ltr",t:{bank:"Modren Bank",dashboard:"Tableau de bord",users:"Utilisateurs",games:"Jeux",currencies:"Monnaies",shop:"Boutique",transactions:"Transactions",permissions:"Autorisations",settings:"Paramètres",backup:"Sauvegarde",login:"Connexion",createAdmin:"Créer l'administrateur",username:"Nom d'utilisateur",password:"Mot de passe",confirm:"Confirmer",logout:"Déconnexion",add:"Ajouter",delete:"Supprimer",freeze:"Geler",active:"Actif",frozen:"Gelé",banned:"Banni",save:"Enregistrer",language:"Langue",theme:"Thème",dark:"Sombre",light:"Clair",warning:"Stockage local du navigateur uniquement",newUser:"Nouvel utilisateur",newGame:"Nouveau jeu",newCurrency:"Nouvelle monnaie",newProduct:"Nouveau produit",name:"Nom",email:"E-mail",code:"ID / code du jeu",symbol:"Symbole",price:"Prix",description:"Description",role:"Rôle",admin:"Admin",user:"Utilisateur",noData:"Aucune donnée",export:"Exporter",import:"Importer",deleteAccount:"Supprimer mon compte",search:"Rechercher",version:"Version",updateUrl:"URL de mise à jour",local:"Mode local uniquement"}},
  es:{name:"Español",dir:"ltr",t:{bank:"Modren Bank",dashboard:"Panel",users:"Usuarios",games:"Juegos",currencies:"Monedas",shop:"Tienda",transactions:"Transacciones",permissions:"Permisos",settings:"Ajustes",backup:"Copia",login:"Iniciar sesión",createAdmin:"Crear administrador",username:"Usuario",password:"Contraseña",confirm:"Confirmar",logout:"Cerrar sesión",add:"Añadir",delete:"Eliminar",freeze:"Congelar",active:"Activo",frozen:"Congelado",banned:"Bloqueado",save:"Guardar",language:"Idioma",theme:"Tema",dark:"Oscuro",light:"Claro",warning:"Solo almacenamiento local del navegador",newUser:"Nuevo usuario",newGame:"Nuevo juego",newCurrency:"Nueva moneda",newProduct:"Nuevo producto",name:"Nombre",email:"Correo",code:"ID / código del juego",symbol:"Símbolo",price:"Precio",description:"Descripción",role:"Rol",admin:"Admin",user:"Usuario",noData:"Sin datos",export:"Exportar",import:"Importar",deleteAccount:"Eliminar mi cuenta",search:"Buscar",version:"Versión",updateUrl:"URL de actualización",local:"Solo local"}},
  zh:{name:"中文",dir:"ltr",t:{bank:"Modren Bank",dashboard:"仪表盘",users:"用户",games:"游戏",currencies:"货币",shop:"商店",transactions:"交易",permissions:"权限",settings:"设置",backup:"备份",login:"登录",createAdmin:"创建管理员",username:"用户名",password:"密码",confirm:"确认密码",logout:"退出",add:"添加",delete:"删除",freeze:"冻结",active:"正常",frozen:"冻结",banned:"封禁",save:"保存",language:"语言",theme:"主题",dark:"深色",light:"浅色",warning:"仅保存在浏览器本地",newUser:"新用户",newGame:"新游戏",newCurrency:"新货币",newProduct:"新产品",name:"名称",email:"邮箱",code:"游戏 ID / 代码",symbol:"符号",price:"价格",description:"描述",role:"角色",admin:"管理员",user:"用户",noData:"暂无数据",export:"导出",import:"导入",deleteAccount:"删除我的账户",search:"搜索",version:"版本",updateUrl:"更新地址",local:"仅本地模式"}},
  it:{name:"Italiano",dir:"ltr",t:{bank:"Modren Bank",dashboard:"Dashboard",users:"Utenti",games:"Giochi",currencies:"Valute",shop:"Negozio",transactions:"Transazioni",permissions:"Permessi",settings:"Impostazioni",backup:"Backup",login:"Accedi",createAdmin:"Crea amministratore",username:"Nome utente",password:"Password",confirm:"Conferma",logout:"Esci",add:"Aggiungi",delete:"Elimina",freeze:"Blocca",active:"Attivo",frozen:"Bloccato",banned:"Bannato",save:"Salva",language:"Lingua",theme:"Tema",dark:"Scuro",light:"Chiaro",warning:"Solo memoria locale del browser",newUser:"Nuovo utente",newGame:"Nuovo gioco",newCurrency:"Nuova valuta",newProduct:"Nuovo prodotto",name:"Nome",email:"E-mail",code:"ID / codice gioco",symbol:"Simbolo",price:"Prezzo",description:"Descrizione",role:"Ruolo",admin:"Admin",user:"Utente",noData:"Nessun dato",export:"Esporta",import:"Importa",deleteAccount:"Elimina il mio account",search:"Cerca",version:"Versione",updateUrl:"URL aggiornamento",local:"Solo locale"}},
  fa:{name:"فارسی",dir:"rtl",t:{bank:"Modren Bank",dashboard:"داشبورد",users:"کاربران",games:"بازی‌ها",currencies:"ارزها",shop:"فروشگاه",transactions:"تراکنش‌ها",permissions:"دسترسی‌ها",settings:"تنظیمات",backup:"پشتیبان",login:"ورود",createAdmin:"ساخت مدیر",username:"نام کاربری",password:"رمز عبور",confirm:"تأیید",logout:"خروج",add:"افزودن",delete:"حذف",freeze:"تجمید",active:"فعال",frozen:"منجمد",banned:"مسدود",save:"ذخیره",language:"زبان",theme:"پوسته",dark:"تیره",light:"روشن",warning:"فقط ذخیره‌سازی محلی مرورگر",newUser:"کاربر جدید",newGame:"بازی جدید",newCurrency:"ارز جدید",newProduct:"محصول جدید",name:"نام",email:"ایمیل",code:"شناسه / کد بازی",symbol:"نماد",price:"قیمت",description:"توضیحات",role:"نقش",admin:"مدیر",user:"کاربر",noData:"داده‌ای نیست",export:"خروجی",import:"ورودی",deleteAccount:"حذف حساب من",search:"جستجو",version:"نسخه",updateUrl:"آدرس بروزرسانی",local:"فقط محلی"}}
};

const blank=()=>({version:4,settings:{lang:"en",theme:"dark",bankName:"Modren Bank",updateUrl:""},users:[],games:[],currencies:[],products:[],transactions:[],permissions:[],session:null});
function load(){try{return JSON.parse(localStorage.getItem(KEY))||blank()}catch{return blank()}}
function id(p){return p+"_"+Math.random().toString(36).slice(2,9)}
async function sha(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function App(){
 const [db,setDb]=useState(load),[page,setPage]=useState("dashboard"),[q,setQ]=useState("");
 const lang=languages[db.settings.lang]||languages.en,t=lang.t;
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(db));document.documentElement.lang=db.settings.lang;document.documentElement.dir=lang.dir;document.documentElement.dataset.theme=db.settings.theme},[db]);
 const admin=db.users.find(u=>u.id===db.session);
 const save=(patch)=>setDb(x=>({...x,...patch}));
 const seed=()=>setDb(x=>({...x,games:x.games.length?x.games:[{id:id("game"),name:"Modren Empire",code:"MODREN-EMPIRE",version:"1.0.0"}],currencies:x.currencies.length?x.currencies:[{id:id("cur"),name:"MOD",symbol:"MOD",gameId:x.games[0]?.id}]}));
 if(!admin){
   return <Auth t={t} langs={languages} lang={db.settings.lang} setLang={v=>save({settings:{...db.settings,lang:v}})}
    hasUsers={db.users.length>0} onLogin={async(u,p)=>{const x=db.users.find(a=>a.username.toLowerCase()===u.toLowerCase());if(x&&(await sha(p))===x.hash&&x.status==="active"){save({session:x.id});return true}return false}}
    onCreate={async(u,p,c)=>{if(p!==c||p.length<8||db.users.some(x=>x.username===u))return false;const x={id:id("usr"),username:u,hash:await sha(p),role:"admin",status:"active"};setDb({...db,users:[x],session:x.id});setTimeout(seed,0);return true}}/>
 }
 const nav=[["dashboard","⌂"],["users","👥"],["games","🎮"],["currencies","◈"],["shop","🛒"],["transactions","↔"],["permissions","🔑"],["settings","⚙"],["backup","💾"]];
 return <div className="app"><header><button className="icon" onClick={()=>document.body.classList.toggle("drawer")}>☰</button><div className="brand"><b>₥</b><strong>{db.settings.bankName}</strong></div><span className="pill">{admin.username}</span><button className="icon" onClick={()=>save({session:null})}>↪</button></header>
 <div className="layout"><aside>{nav.map(([p,i])=><button className={page===p?"active":""} onClick={()=>setPage(p)} key={p}>{i} {t[p]}</button>)}</aside><main>
 {page==="dashboard"&&<Dashboard db={db} t={t} setPage={setPage}/>}
 {page==="users"&&<Users db={db} setDb={setDb} t={t} q={q} setQ={setQ}/>}
 {page==="games"&&<Games db={db} setDb={setDb} t={t}/>}
 {page==="currencies"&&<Currencies db={db} setDb={setDb} t={t}/>}
 {page==="shop"&&<Shop db={db} setDb={setDb} t={t}/>}
 {page==="transactions"&&<Section title={t.transactions}><Table rows={db.transactions} empty={t.noData}/></Section>}
 {page==="permissions"&&<Permissions db={db} setDb={setDb} t={t}/>}
 {page==="settings"&&<Settings db={db} setDb={setDb} t={t} langs={languages}/>}
 {page==="backup"&&<Backup db={db} setDb={setDb} t={t}/>}
 </main></div></div>
}
function Auth({t,langs,lang,setLang,hasUsers,onLogin,onCreate}){const [u,setU]=useState(""),[p,setP]=useState(""),[c,setC]=useState(""),[err,setErr]=useState("");return <div className="auth"><form className="authbox" onSubmit={async e=>{e.preventDefault();const ok=hasUsers?await onLogin(u,p):await onCreate(u,p,c);if(!ok)setErr("Check the entered information.")}}><div className="authlogo">₥</div><h1>Modren Bank</h1><p className="muted">{hasUsers?t.login:t.createAdmin}</p><input placeholder={t.username} value={u} onChange={e=>setU(e.target.value)} required/><input placeholder={t.password} type="password" value={p} onChange={e=>setP(e.target.value)} required/>{!hasUsers&&<input placeholder={t.confirm} type="password" value={c} onChange={e=>setC(e.target.value)} required/>}<button className="primary">{hasUsers?t.login:t.createAdmin}</button>{err&&<p className="error">{err}</p>}<select value={lang} onChange={e=>setLang(e.target.value)}>{Object.entries(langs).map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select><small>{t.warning}</small></form></div>}
function Section({title,children,actions}){return <><div className="head"><div><h1>{title}</h1></div>{actions}</div>{children}</>}
function Card({label,value,icon}){return <div className="card"><small>{icon} {label}</small><strong>{value}</strong></div>}
function Dashboard({db,t,setPage}){return <Section title={t.dashboard}><div className="cards"><Card label={t.users} value={db.users.length} icon="👥"/><Card label={t.games} value={db.games.length} icon="🎮"/><Card label={t.currencies} value={db.currencies.length} icon="◈"/><Card label={t.shop} value={db.products.length} icon="🛒"/><Card label={t.transactions} value={db.transactions.length} icon="↔"/></div><div className="panel quick"><h2>Quick actions</h2><button onClick={()=>setPage("users")}>{t.newUser}</button><button onClick={()=>setPage("games")}>{t.newGame}</button><button onClick={()=>setPage("currencies")}>{t.newCurrency}</button><button onClick={()=>setPage("shop")}>{t.newProduct}</button></div></Section>}
function Users({db,setDb,t,q,setQ}){const [form,setForm]=useState({username:"",email:"",password:"",role:"user"});const rows=db.users.filter(x=>x.username.toLowerCase().includes(q.toLowerCase()));async function add(e){e.preventDefault();if(!form.username||form.password.length<8)return;const x={id:id("usr"),...form,hash:await sha(form.password),status:"active"};delete x.password;setDb({...db,users:[...db.users,x]});setForm({username:"",email:"",password:"",role:"user"})}return <Section title={t.users}><div className="panel"><input placeholder={t.search} value={q} onChange={e=>setQ(e.target.value)}/><form className="formrow" onSubmit={add}><input placeholder={t.username} value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input placeholder={t.email} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder={t.password} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button className="primary">{t.add}</button></form><Table rows={rows} empty={t.noData} extra={x=><><span>{x.status}</span>{x.role!=="admin"&&<button className="mini" onClick={()=>setDb({...db,users:db.users.filter(u=>u.id!==x.id)})}>{t.delete}</button>}</>}/></div></Section>}
function Games({db,setDb,t}){const [f,setF]=useState({name:"",code:"",version:"1.0.0"});return <Section title={t.games}><div className="panel formrow"><input placeholder={t.name} value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input placeholder={t.code} value={f.code} onChange={e=>setF({...f,code:e.target.value})}/><input placeholder={t.version} value={f.version} onChange={e=>setF({...f,version:e.target.value})}/><button className="primary" onClick={()=>{if(f.name&&f.code){setDb({...db,games:[...db.games,{id:id("game"),...f}]});setF({name:"",code:"",version:"1.0.0"})}}}>{t.add}</button></div><Table rows={db.games} empty={t.noData}/></Section>}
function Currencies({db,setDb,t}){const [f,setF]=useState({name:"MOD",symbol:"MOD",gameId:db.games[0]?.id||""});return <Section title={t.currencies}><div className="panel formrow"><input placeholder={t.name} value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input placeholder={t.symbol} value={f.symbol} onChange={e=>setF({...f,symbol:e.target.value})}/><select value={f.gameId} onChange={e=>setF({...f,gameId:e.target.value})}>{db.games.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><button className="primary" onClick={()=>{if(f.name&&f.symbol){setDb({...db,currencies:[...db.currencies,{id:id("cur"),...f}]})}}}>{t.add}</button></div><Table rows={db.currencies} empty={t.noData}/></Section>}
function Shop({db,setDb,t}){const [f,setF]=useState({name:"",price:0,currencyId:db.currencies[0]?.id||""});return <Section title={t.shop}><p className="muted">Products are managed here for the local bank demo. In Modren Empire, the real in-game shop remains managed inside the game.</p><div className="panel formrow"><input placeholder={t.name} value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input placeholder={t.price} type="number" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/><select value={f.currencyId} onChange={e=>setF({...f,currencyId:e.target.value})}>{db.currencies.map(c=><option key={c.id} value={c.id}>{c.symbol}</option>)}</select><button className="primary" onClick={()=>{if(f.name)setDb({...db,products:[...db.products,{id:id("prd"),...f}]})}}>{t.add}</button></div><Table rows={db.products} empty={t.noData}/></Section>}
function Permissions({db,setDb,t}){const [f,setF]=useState({userId:"",gameId:"",unlimited:true});return <Section title={t.permissions}><div className="panel formrow"><select onChange={e=>setF({...f,userId:e.target.value})}><option value="">User</option>{db.users.map(u=><option key={u.id} value={u.id}>{u.username}</option>)}</select><select onChange={e=>setF({...f,gameId:e.target.value})}><option value="">Game</option>{db.games.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><button className="primary" onClick={()=>{if(f.userId&&f.gameId)setDb({...db,permissions:[...db.permissions,{id:id("perm"),...f}]})}}>Grant unlimited</button></div><Table rows={db.permissions} empty={t.noData}/></Section>}
function Settings({db,setDb,t,langs}){return <Section title={t.settings}><div className="panel form"><label>{t.language}<select value={db.settings.lang} onChange={e=>setDb({...db,settings:{...db.settings,lang:e.target.value}})}>{Object.entries(langs).map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select></label><label>{t.theme}<select value={db.settings.theme} onChange={e=>setDb({...db,settings:{...db.settings,theme:e.target.value}})}><option value="dark">{t.dark}</option><option value="light">{t.light}</option></select></label><label>{t.name}<input value={db.settings.bankName} onChange={e=>setDb({...db,settings:{...db.settings,bankName:e.target.value}})}/></label><label>{t.updateUrl}<input value={db.settings.updateUrl} onChange={e=>setDb({...db,settings:{...db.settings,updateUrl:e.target.value}})}/></label></div></Section>}
function Backup({db,setDb,t}){function exp(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:"application/json"}));a.download="modren-bank-backup.json";a.click()}function imp(e){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(x.users&&x.settings)setDb(x)}catch{alert("Invalid backup")}};r.readAsText(e.target.files[0])}return <Section title={t.backup}><div className="panel actions"><button className="primary" onClick={exp}>{t.export}</button><input type="file" accept=".json" onChange={imp}/></div></Section>}
function Table({rows,empty,extra}){if(!rows?.length)return <div className="empty">{empty}</div>;return <div className="tablewrap"><table><thead><tr><th>Name / ID</th><th>Status / details</th><th>Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.name||x.username||x.id}</b></td><td>{x.symbol||x.status||x.code||x.version||x.unlimited?" "+(x.symbol||x.status||x.code||x.version||"Unlimited"):"—"}</td><td>{extra?extra(x):null}</td></tr>)}</tbody></table></div>}

export default App;
